using System.Text;
using Content.Shared._DEN.Language;
using Content.Shared._DEN.Language.EntitySystems;
using Content.Shared._DEN.Requirements.Managers;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Range = Robust.Client.UserInterface.Controls.Range;

namespace Content.Client._DEN.Lobby.UI.Languages;

[GenerateTypedNameReferences]
public sealed partial class LanguageSelector : BoxContainer
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IPlayerManager _player = default!;
    [Dependency] private IPlayerRequirementManager _requirements = default!;

    public event Action<HumanoidCharacterProfile?>? OnPreferenceUpdated;

    private HumanoidCharacterProfile? _profile;
    private LanguageEntryPrototype _entryProto;
    private LanguagePrototype? _langProto;
    private List<LanguageFluencyPrototype> _langFluencies;
    private LanguagePreference _langPreference;
    private int _points;
    private int _maxPoints;

    public LanguageSelector(HumanoidCharacterProfile? profile, LanguageEntryPrototype entryProto, List<LanguageFluencyPrototype> langFluencies, int? points, int? maxPoints)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _entryProto = entryProto;
        _langFluencies = langFluencies;
        _profile = profile;
        _points = points ?? 0;
        _maxPoints = maxPoints ?? SharedLanguageSystem.LanguageSelectionPoints;
        LanguagePreference? preference = null;
        if (_profile?.LanguagePreferences.TryGetValue(entryProto.ID, out var prefVal) is true)
            preference = prefVal;
        _langPreference = preference ?? new LanguagePreference(SharedLanguageSystem.MinimumFluency, SpokenState.None, false);

        Initialize();
    }

    private void Initialize()
    {
        var context = GetContext();
        if (SharedPlayerRequirementManager.ShouldHide(context, _entryProto.Requirements))
        {
            Visible = false;
            return;
        }

        if (!SharedPlayerRequirementManager.CheckRequirements(context, _entryProto.Requirements))
        {
            SpeaksOptionButton.Disabled = true;
            FluencySlider.Disabled = true;
            PrimaryButton.Disabled = true;
        }
        
        _langProto = _prototypeManager.Index(_entryProto.LanguageProto);
        LanguageNameLabel.Text = _langProto.LocalizedName;
        LanguageNameLabel.ToolTip = _langProto.LocalizedDescription;
        LanguageNameLabel.MouseFilter = MouseFilterMode.Pass;
        
        SpeaksOptionButton.AddItem(Loc.GetString("language-selector-none-text"), 0);
        SpeaksOptionButton.AddItem(Loc.GetString("language-selector-spoken-text"), 1);
        SpeaksOptionButton.AddItem(Loc.GetString("language-selector-translator-text"), 2);
        SpeaksOptionButton.SelectId((int) _langPreference.Speaks);
        SpeaksOptionButton.OnItemSelected += args =>
        {
            SpeaksOptionButton.SelectId(args.Id);
            LanguageSpeechPreferenceUpdated();
        };
        
        if (!SharedPlayerRequirementManager.CheckRequirements(context, _entryProto.SpeakingRequirements))
            SpeaksOptionButton.SetItemDisabled(1, true);
        
        if (!_entryProto.CanHaveTranslator)
            SpeaksOptionButton.SetItemDisabled(2, true);

        PrimaryButton.Pressed = _langPreference.Primary;
        PrimaryButton.OnPressed += _ => LanguagePrimaryPreferenceUpdated();

        FluencySlider.MaxValue = _langFluencies.Count - 1;
        FluencySlider.LockMaxValue = FluencySlider.MaxValue;
        FluencySlider.LockMinValue = 0;
        FluencySlider.Value = _langFluencies.FindIndex(l => l.ID == _langPreference.Fluency);
        FluencySlider.OnValueChanged += FluencySliderChanged;
        FluencySlider.OnReleased += _ => LanguageFluencyPreferenceUpdated();

        if (_prototypeManager.TryIndex(_langPreference.Fluency, out var fluency))
            LanguageFluencyLabel.Text = Loc.GetString(fluency.Name);
        
        var availablePoints = _maxPoints - _points;
        LimitFluencySlider(availablePoints);
        LimitSpeechOptions(availablePoints);
        LimitPrimaryButton(availablePoints);
    }

    private PlayerRequirementContext GetContext()
    {
        var session = _player.LocalSession;
        if (session == null)
            return new();

        var context = _requirements.GetPlayerContext(session);
        return context;
    }

    private void LimitFluencySlider(int availablePoints)
    {
        switch (availablePoints)
        {
            case 0:
                if (_langPreference.Fluency == SharedLanguageSystem.MinimumFluency)
                    FluencySlider.LockMaxValue = 1;
                else if (_langPreference.Fluency != SharedLanguageSystem.MaximumFluency)
                    FluencySlider.LockMaxValue = _langFluencies.Count - 2;
                break;
            case 1:
                if (_langPreference.Fluency == SharedLanguageSystem.MinimumFluency)
                    FluencySlider.LockMaxValue = _langFluencies.Count - 2;
                break;
        }

        if (PrimaryButton.Pressed)
            FluencySlider.LockMinValue = _langFluencies.Count - 1;
    }

    private void LimitSpeechOptions(int availablePoints)
    {
        switch (availablePoints)
        {
            case 0:
                // Can't spend a point to speak if we're not already on speaks.
                if (_langPreference.Speaks == SpokenState.None)
                {
                    SpeaksOptionButton.SetItemDisabled(1, true);
                    SpeaksOptionButton.SetItemDisabled(2, true);
                }
                break;
            case 1:
                // Can only turn on speech at 1 point if we're already fluent.
                if (_langPreference.Speaks != SpokenState.Speaks && _langPreference.Fluency != SharedLanguageSystem.MaximumFluency)
                    SpeaksOptionButton.SetItemDisabled(1, true);
                break;
            case 2:
                if (_langPreference.Fluency == SharedLanguageSystem.MinimumFluency)
                    SpeaksOptionButton.SetItemDisabled(1, true);
                break;
        }
    }

    private void LimitPrimaryButton(int availablePoints)
    {
        switch (availablePoints)
        {
            case 0:
                if (_langPreference.Speaks == SpokenState.None || 
                    (_langPreference.Fluency != SharedLanguageSystem.MaximumFluency && _langPreference.Speaks == SpokenState.Translator))
                    PrimaryButton.Disabled = true;
                break;
            case 1:
                if (_langPreference.Fluency != SharedLanguageSystem.MaximumFluency)
                    PrimaryButton.Disabled = true;
                break;
            case 2:
                if (_langPreference.Fluency == SharedLanguageSystem.MinimumFluency)
                    PrimaryButton.Disabled = true;
                break;
        }
    }

    private void FluencySliderChanged(Range range)
    {
        var fluency = (int)range.Value;
        LanguageFluencyLabel.Text = Loc.GetString(_langFluencies[fluency].Name);
    }

    private void LanguageSpeechPreferenceUpdated()
    {
        var spokenState = (SpokenState)SpeaksOptionButton.SelectedId;
        _profile = _profile?.WithLanguageSpeechPreference(_entryProto.ID, spokenState);
        
        OnPreferenceUpdated?.Invoke(_profile);
    }
    
    private void LanguageFluencyPreferenceUpdated()
    {
        var fluency = _langFluencies[(int)FluencySlider.Value].ID;
        _profile = _profile?.WithLanguageFluency(_entryProto.ID, fluency);
        
        OnPreferenceUpdated?.Invoke(_profile);
    }
    
    private void LanguagePrimaryPreferenceUpdated()
    {
        var primary = PrimaryButton.Pressed;
        _profile = _profile?.WithLanguagePrimary(_entryProto.ID, primary);
        
        OnPreferenceUpdated?.Invoke(_profile);
    }
}
