using Content.Shared._DEN.Language;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Range = Robust.Client.UserInterface.Controls.Range;

namespace Content.Client._DEN.Lobby.UI.Languages;

[GenerateTypedNameReferences]
public sealed partial class LanguageSelector : BoxContainer
{
    private readonly IPrototypeManager _prototypeManager;

    private LanguageEntryPrototype _entryProto;
    private LanguagePrototype? _langProto;
    private List<LanguageFluencyPrototype> _langFluencies;

    public LanguageSelector(IPrototypeManager prototypeManager, LanguageEntryPrototype entryProto, List<LanguageFluencyPrototype> langFluencies)
    {
        RobustXamlLoader.Load(this);
        _prototypeManager = prototypeManager;
        _entryProto = entryProto;
        _langFluencies = langFluencies;

        Initialize();
    }

    private void Initialize()
    {
        _langProto = _prototypeManager.Index(_entryProto.LanguageProto);
        LanguageNameLabel.Text = _langProto.LocalizedName;
        LanguageNameLabel.ToolTip = _langProto.LocalizedDescription;
        LanguageNameLabel.MouseFilter = MouseFilterMode.Pass;

        FluencySlider.MaxValue = _langFluencies.Count - 1;
        FluencySlider.OnValueChanged += FluencySliderChanged;
        LanguageFluencyLabel.Text = Loc.GetString(_langFluencies[0].Name);
    }

    private void FluencySliderChanged(Range range)
    {
        var fluency = (int)range.Value;
        LanguageFluencyLabel.Text = Loc.GetString(_langFluencies[fluency].Name);
    }
}
