using System.Numerics;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._DEN.Lobby.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class SkinColorSliders : BoxContainer
{
    [Dependency] private IPrototypeManager _protoMan = default!;

    public event Action<Color>? OnColorChanged;

    private SkinColorationPrototype? _skinColor = null;
    private ISkinColorationStrategy? _currentStrategy = null;

    public SkinColorSliders()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ColorSliders.OnColorChanged += _ => { OnSliderValueChanged(); };
        LinearSlider.OnValueChanged += _ => { OnSliderValueChanged(); };
        ToggleAltStrategyButton.OnToggled += args => { OnAltStrategyToggled(); };
    }

    public void SetSkinColoration(ProtoId<SpeciesPrototype> protoId)
    {
        if (!_protoMan.Resolve(protoId, out var species))
            return;

        SetSkinColoration(species.SkinColoration);
    }

    public void SetSkinColoration(ProtoId<SkinColorationPrototype> protoId)
    {
        if (!_protoMan.Resolve(protoId, out var skinColor))
            return;

        _skinColor = skinColor;

        var currentColor = GetCurrentColor();
        var useAlt = _skinColor.AltStrategy != null && PreferAltStrategyForColor(currentColor);
        var strategy = useAlt ? _skinColor.AltStrategy : _skinColor.Strategy;
        _currentStrategy = strategy;

        UpdateVisibleStrategy();
        SetSliderColor(currentColor);
    }

    public void SetSkinColor(Color color)
    {
        if (_skinColor is null)
            return;

        var useAlt = _skinColor.AltStrategy != null && PreferAltStrategyForColor(color);
        var strategy = useAlt ? _skinColor.AltStrategy : _skinColor.Strategy;
        _currentStrategy = strategy;

        UpdateVisibleStrategy();
        SetSliderColor(color);
    }

    private void SetSliderColor(Color color)
    {
        if (_currentStrategy is null)
            return;

        switch (_currentStrategy.InputType)
        {
            case SkinColorationStrategyInput.Unary:
                var sliderValue = _currentStrategy.ToUnary(color);
                LinearSlider.SetValueWithoutEvent(sliderValue);
                break;

            case SkinColorationStrategyInput.Color:
                ColorSliders.Color = color;
                break;
        }
    }

    private void OnSliderValueChanged()
    {
        if (_skinColor is null)
            return;

        var color = GetCurrentColor();
        OnColorChanged?.Invoke(color);
    }

    private void OnAltStrategyToggled()
    {
        if (_skinColor is null)
            return;

        var currentColor = GetCurrentColor();

        // Can't enable alt strategies if this skin coloration doesn't have one.
        if (_skinColor.AltStrategy == null)
        {
            ToggleAltStrategyButton.Pressed = false;
            _currentStrategy = _skinColor.Strategy;
            UpdateVisibleStrategy();
            SetSliderColor(currentColor);
            return;
        }

        // Update the alt strategy.
        var enabled = ToggleAltStrategyButton.Pressed;
        _currentStrategy = enabled ? _skinColor.AltStrategy : _skinColor.Strategy;

        UpdateVisibleStrategy();
        SetSliderColor(currentColor);
    }

    private Color GetCurrentColor()
    {
        var color = Color.White;

        if (_skinColor is null)
            return color;

        var useAlt = AltStrategyIsActive();
        var strategy = useAlt && _skinColor.AltStrategy != null
            ? _skinColor.AltStrategy
            : _skinColor.Strategy;

        switch (strategy.InputType)
        {
            case SkinColorationStrategyInput.Unary:
                color = GetUnaryColor(strategy);
                break;

            case SkinColorationStrategyInput.Color:
                color = GetRgbColor(strategy);
                break;

            default:
                throw new ArgumentOutOfRangeException(nameof(strategy.InputType));
        }

        return color;
    }

    private Color GetUnaryColor(ISkinColorationStrategy strategy)
    {
        var sliderValue = LinearSlider.Value;
        var color = strategy.FromUnary(sliderValue);

        return color;
    }

    private Color GetRgbColor(ISkinColorationStrategy strategy)
    {
        var sliderValue = ColorSliders.Color;
        var color = strategy.ClosestSkinColor(sliderValue);

        return color;
    }

    private bool PreferAltStrategyForColor(Color color)
    {
        if (_skinColor is null || _skinColor.AltStrategy is null)
            return false;

        var primary = _skinColor.Strategy;
        var alt = _skinColor.AltStrategy;

        // If the color is valid for one strategy but not the other,
        // we should use the valid strategy.
        var primaryValid = primary.VerifySkinColor(color, out var _);
        var altValid = alt.VerifySkinColor(color, out var _);

        if (primaryValid && !altValid)
            return false;

        if (!primaryValid && altValid)
            return true;

        // Otherwise, this color is either valid for both strategies, or invalid for both.
        // We should use the strategy with the closer "accurate" color.
        var primaryClosest = GetClosestColorForStrategy(primary, color) with { A = color.A };
        var primaryDistance = GetColorDistance(color, primaryClosest);

        var altClosest = GetClosestColorForStrategy(alt, color) with { A = color.A };
        var altDistance = GetColorDistance(color, altClosest);

        // If the alternate strategy is closer, then we're using it.
        return altDistance < primaryDistance;
    }

    private bool AltStrategyIsActive()
    {
        return _skinColor?.AltStrategy is not null
            && ToggleAltStrategyButton.Pressed;
    }

    private void UpdateVisibleStrategy()
    {
        if (_skinColor is null)
            return;

        ToggleAltStrategyButton.Visible = _skinColor.AltStrategy is not null;

        if (_currentStrategy is null)
            return;

        switch (_currentStrategy.InputType)
        {
            case SkinColorationStrategyInput.Unary:
                LinearSliderBox.Visible = true;
                ColorSliderBox.Visible = false;
                break;

            case SkinColorationStrategyInput.Color:
                LinearSliderBox.Visible = false;
                ColorSliderBox.Visible = true;
                break;
        }
    }

    private static Color GetClosestColorForStrategy(ISkinColorationStrategy strategy, Color color)
    {
        var inputType = strategy.InputType;
        // TODO: why doesnt ISkinColorationStrategy just have a method for this
        return inputType switch
        {
            SkinColorationStrategyInput.Color => strategy.ClosestSkinColor(color),
            SkinColorationStrategyInput.Unary => strategy.FromUnary(strategy.ToUnary(color)),
            _ => throw new ArgumentOutOfRangeException(nameof(strategy)),
        };
    }

    private static float GetColorDistance(Color a, Color b)
    {
        // TODO: why isnt this a static color method also
        var va = a.RGBA;
        var vb = b.RGBA;
        var diff = va - vb;
        return Vector4.Dot(diff, diff);
    }
}
