using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._DEN.Lobby.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class SkinColorSliders : BoxContainer
{
    [Dependency] private IPrototypeManager _protoMan = default!;

    private SkinColorationPrototype? _skinColor = null;

    public SkinColorSliders()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetStrategyFromSpecies(ProtoId<SpeciesPrototype> protoId)
    {
        if (!_protoMan.Resolve(protoId, out var species))
            return;

        SetStrategy(species.SkinColoration);
    }

    public void SetStrategy(ProtoId<SkinColorationPrototype> protoId)
    {
        if (!_protoMan.Resolve(protoId, out var skinColor))
            return;

        _skinColor = skinColor;
        UpdateSliderVisuals();
    }

    private void UpdateSliderVisuals()
    {
        if (_skinColor is null)
            return;

        ToggleAltStrategyButton.Visible = _skinColor.AltStrategy is not null;
    }
}
