using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.UserInterface.Systems.Language.Windows;

[GenerateTypedNameReferences]
public sealed partial class LanguageWindow : DefaultWindow
{
    public LanguageWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
