using Content.Client._DEN.Language.EntitySystems;
using Content.Shared._DEN.Language.Components;
using Content.Shared.Examine;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._DEN.UserInterface.Systems.Language.Controls;

[GenerateTypedNameReferences]
public sealed partial class LanguageContainer : Control
{
    private IEntityManager _entities;
    private IPlayerManager _player;
    private IPrototypeManager _proto;
    private LanguageSystem _language;

    public event Action? SpeakPressed;

    public Entity<LanguageComponent>? LanguageEnt { get; private set; }

    public LanguageContainer(IEntityManager entities, IPlayerManager player, IPrototypeManager proto, LanguageSystem language)
    {
        _entities = entities;
        _player = player;
        _proto = proto;
        _language = language;

        RobustXamlLoader.Load(this);
        
        LanguageButton.OnPressed += _ => SpeakPressed?.Invoke();
        SpeakPressed += OnLanguageChosen;
    }

    public void UpdateLanguage(Entity<LanguageComponent> language)
    {
        LanguageEnt = language;
        UpdateData();
    }

    public void SetCurrentSpoken(bool current)
    {
        LanguageButton.Visible = !current;
    }

    private void UpdateData()
    {
        if (LanguageEnt == null || _player.LocalEntity == null)
            return;

        var langProto = _proto.Index(LanguageEnt.Value.Comp.Language);
        var fluencyProto = _proto.Index(LanguageEnt.Value.Comp.Fluency);

        LanguageName.Text = langProto.LocalizedName;

        LanguageButton.Disabled = !LanguageEnt.Value.Comp.Speaks;

        var desc = FormattedMessage.FromMarkupPermissive(
            Loc.GetString("language-ui-language-fluency",
                ("fluency", Loc.GetString(fluencyProto.Name)),
                ("color", Color.InterpolateBetween(Color.Red, Color.Green, (float)(fluencyProto.Understanding / 100.0)))));
        desc.PushNewline();
        desc.AddMarkupPermissive(langProto.LocalizedDescription);

        var ev = new ExaminedEvent(desc, LanguageEnt.Value, _player.LocalEntity.Value, true, !desc.IsEmpty);
        _entities.EventBus.RaiseLocalEvent(LanguageEnt.Value, ev);

        Description.SetMessage(ev.GetTotalMessage());
    }

    private void OnLanguageChosen()
    {
        if (LanguageEnt != null)
            _language.TrySetSpokenLanguage(LanguageEnt.Value);
    }
}
