using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Numerics;
using Content.Client._DEN.Modules.EntitySystems;
using Content.Client.Hands.Systems;
using Content.Client.Resources;
using Content.Client.UserInterface.Controls;
using Content.Shared._DEN.Modules.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Timing;

namespace Content.Client._DEN.Modules.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class ModuleStorageWindow : FancyWindow
{
    [Dependency] private readonly IResourceCache _resourceCache = default!;
    [Dependency] private readonly IEntityManager _entity = default!;

    public Entity<ModuleStorageComponent>? ModControlEntity;

    public event Action<int>? OnSlotClicked;
    
    private readonly string _leftTexturePath = "/Textures/_DEN/Interface/Modules/module-background-left.png";
    private Texture? _leftTexture;
    private readonly string _middleTexturePath = "/Textures/_DEN/Interface/Modules/module-background-middle.png";
    private Texture? _middleTexture;
    private readonly string _rightTexturePath = "/Textures/_DEN/Interface/Modules/module-background-right.png";
    private Texture? _rightTexture;

    private int _busSize = 0;

    private readonly Dictionary<EntityUid, (int, Control)> _modules = new();
    private readonly List<Control> _controlGrid = new();
    
    public ModuleStorageWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        
        _leftTexture = _resourceCache.GetTexture(_leftTexturePath);
        _middleTexture = _resourceCache.GetTexture(_middleTexturePath);
        _rightTexture = _resourceCache.GetTexture(_rightTexturePath);
    }

    public void Initialize(Entity<ModuleStorageComponent> entity)
    {
        ModControlEntity = entity;
        _busSize = entity.Comp.MaxBusWidth;
        BuildBackground(_busSize);
    }

    private void BuildBackground(int busSize)
    {
        BackgroundGrid.Columns = busSize;
        ModuleGrid.Columns = busSize;
        
        BackgroundGrid.AddChild(new TextureRect
        {
            Texture = _leftTexture,
            TextureScale = new Vector2(2, 2)
        });
        for (var i = 1; i < busSize-1; i++)
        {
            BackgroundGrid.AddChild(new TextureRect
            {
                Texture = _middleTexture,
                TextureScale = new Vector2(2, 2)
            });
        }
        BackgroundGrid.AddChild(new TextureRect
        {
            Texture = _rightTexture,
            TextureScale = new Vector2(2, 2)
        });
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var handsSystem = _entity.System<HandsSystem>();
        var modsuitSystem = _entity.System<ModuleStorageSystem>();

        foreach (var child in BackgroundGrid.Children)
        {
            child.ModulateSelfOverride = null;
        }
        
        if (UserInterfaceManager.CurrentlyHovered != this || ModControlEntity == null)
            return;
        
        if (handsSystem.GetActiveHandEntity() is { } handsEntity)
        {
            if (!_entity.TryGetComponent<ModuleComponent>(handsEntity, out var moduleComp))
                return;

            var location = GetMouseModuleLocation();
            var isValid = modsuitSystem.ModuleFitsInStorage(ModControlEntity.Value, handsEntity, location.X);
            var color = isValid ? Color.Aqua : Color.Red;
            for (var x = 0; x < _busSize; x++)
            {
                if (TryGetBackgroundModule(x, out var module))
                {
                    if (location.Y == 0 && x >= location.X && x < (location.X + moduleComp.BusWidth))
                    {
                        module.ModulateSelfOverride = color;
                    }
                }
            }
        }
    }

    private bool TryGetBackgroundModule(int x, [NotNullWhen(true)] out Control? module)
    {
        module = null;
        if (x < 0 || x >= _busSize)
            return false;

        module = BackgroundGrid.GetChild(x);
        return true;
    }

    private Vector2i GetMouseModuleLocation()
    {
        var textureSize = (Vector2) _middleTexture!.Size * 2;
        return ((UserInterfaceManager.MousePositionScaled.Position - BackgroundGrid.GlobalPosition) / textureSize).Floored();
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (args.Function != EngineKeyFunctions.UIClick || ModControlEntity == null)
            return;
        
        var handsSystem = _entity.System<HandsSystem>();
        var modsuitSystem = _entity.System<ModuleStorageSystem>();

        if (handsSystem.GetActiveHandEntity() is not { } handEntity)
            return;
        
        var location = GetMouseModuleLocation();
        if (location.Y != 0)
            return;
        
        var slot = location.X;
        if (modsuitSystem.ModuleFitsInStorage(ModControlEntity.Value, handEntity, slot))
        {
            OnSlotClicked?.Invoke(slot);
            args.Handle();
        }
    }

    private void OnModulePressed(EntityUid module)
    {
        OnSlotClicked?.Invoke(_modules[module].Item1);
    }

    public void Update()
    {
        if (ModControlEntity == null)
            return;
        
        var size = _middleTexture!.Size * 2;
        
        ModuleGrid.Columns = ModControlEntity.Value.Comp.MaxBusWidth;
        ModuleGrid.RemoveAllChildren();
        _controlGrid.Clear();
        for (var i = 0; i < _busSize; i++)
        {
            var control = new Control
            {
                MinSize = size
            };
            
            _controlGrid.Add(control);
            ModuleGrid.AddChild(control);
        }

        var moduleSlots = ModControlEntity.Value.Comp.ModuleSlots;
        
        List<EntityUid> toRemove = new();
        foreach (var (ent, data) in _modules)
        {
            if (moduleSlots.ContainsValue(ent))
            {
                var curSlot = moduleSlots.Where(kvp => kvp.Value == ent).MinBy(kvp => kvp.Key).Key;
                
                data.Item2.Orphan();
                _controlGrid[curSlot].AddChild(data.Item2);
                _modules[ent] = (curSlot, data.Item2);
                
                continue;
            }
            toRemove.Add(ent);
        }

        foreach (var ent in toRemove)
        {
            _modules.Remove(ent, out var data);
            data.Item2.Orphan();
        }

        toRemove.Clear();

        foreach (var (slot, ent) in moduleSlots)
        {
            if (ent == null)
                continue;
            
            if (_modules.TryGetValue(ent.Value, out var existing))
            {
                continue;
            }

            if (_entity.TryGetComponent<ModuleComponent>(ent, out var moduleComp))
            {
                var modulePiece = new ModuleGridPiece((ent.Value, moduleComp), _entity, _resourceCache)
                {
                    MinSize = size,
                };
                modulePiece.OnModuleClicked += OnModulePressed;
                _controlGrid[slot].AddChild(modulePiece);
                _modules[ent.Value] = (slot, modulePiece);
            }
        }
    }
}