using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._DEN.Modules.Components;
using Content.Shared.Item.ItemToggle.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Clothing.Modsuits.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class ModsuitControllerWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entity = default!;
    
    private Entity<ModuleStorageComponent>? _modControlEntity;

    private Dictionary<EntityUid, (SwitchButton, Label)> _gridControls = new();

    public Action<EntityUid, bool>? OnModuleToggled;
    
    public ModsuitControllerWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void Initialize(Entity<ModuleStorageComponent> entity)
    {
        _modControlEntity = entity;
        Update();
    }

    public void Update()
    {
        if (_modControlEntity == null)
            return;

        var seen = new Dictionary<EntityUid, bool>();
        foreach (var entUid in _gridControls.Keys)
        {
            seen[entUid] = false;
        }
        
        foreach (var module in _modControlEntity.Value.Comp.ModuleSlots.Values)
        {
            if (module is null)
                continue;

            if (_entity.TryGetComponent<ItemToggleComponent>(module, out var toggleComp))
            {
                if (_gridControls.TryGetValue(module.Value, out var controls))
                {
                    controls.Item1.Pressed = toggleComp.Activated;
                    seen[module.Value] = true;
                } 
                else
                {
                    var button = new SwitchButton
                    {
                        ToggleMode = true,
                        Pressed = toggleComp.Activated,
                        MinWidth = 100.0f
                    };
                    button.OnToggled += e => OnModuleToggled?.Invoke(module.Value, e.Pressed);
                    var label = new Label
                    {
                        Text = _entity.GetComponent<MetaDataComponent>(module.Value).EntityName,
                    };
                    ToggleGrid.AddChild(button);
                    ToggleGrid.AddChild(label);
                    _gridControls.Add(module.Value, (button, label));
                }
            }
        }

        foreach (var entUpdated in seen)
        {
            if (entUpdated.Value)
                continue;
            
            var controls = _gridControls[entUpdated.Key];
            ToggleGrid.RemoveChild(controls.Item1);
            ToggleGrid.RemoveChild(controls.Item2);
            _gridControls.Remove(entUpdated.Key);
        }
    }
}