using System.Numerics;
using Content.Client.Hands.Systems;
using Content.Client.Resources;
using Content.Client.UserInterface.Controls;
using Content.Shared._DEN.Clothing.Modsuits.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._DEN.Clothing.Modsuits.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class ModsuitModuleWindow : FancyWindow
{
    [Dependency] private readonly IResourceCache _resourceCache = default!;
    [Dependency] private readonly HandsSystem _handsSystem = default!;
    [Dependency] private readonly IEntityManager _entity = default!;
    
    public ModsuitModuleWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void BuildBackground(int busSize)
    {
        BackgroundGrid.Columns = busSize;
        ModuleGrid.Columns = busSize;
        var leftTex = _resourceCache.GetTexture("/Textures/_DEN/Interface/Modsuits/module-background-left.png");
        var midTex = _resourceCache.GetTexture("/Textures/_DEN/Interface/Modsuits/module-background-middle.png");
        var rightTex = _resourceCache.GetTexture("/Textures/_DEN/Interface/Modsuits/module-background-right.png");
        
        BackgroundGrid.AddChild(new TextureRect
        {
            Texture = leftTex,
            TextureScale = new Vector2(2, 2)
        });
        for (var i = 1; i < busSize-1; i++)
        {
            BackgroundGrid.AddChild(new TextureRect
            {
                Texture = midTex,
                TextureScale = new Vector2(2, 2)
            });
        }
        BackgroundGrid.AddChild(new TextureRect
        {
            Texture = rightTex,
            TextureScale = new Vector2(2, 2)
        });
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_handsSystem.GetActiveHandEntity() is { } handsEntity)
        {
            
        }
    }

    public void Populate(Entity<ModsuitControlComponent> entity)
    {
        
    }
}