using System.Numerics;
using Content.Client.Power.EntitySystems;
using Content.Client.UserInterface.Controls;
using Content.Shared._DEN.Clothing.Modsuits.Components;
using Content.Shared._DEN.Modules.Components;
using Content.Shared.IdentityManagement;
using Content.Shared.Item.ItemToggle.Components;
using Content.Shared.PowerCell;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._DEN.Clothing.Modsuits.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class ModsuitControllerWindow : FancyWindow
{
    [Dependency] private IEntityManager _entity = default!;
    
    private Entity<ModsuitControllerComponent, ModuleStorageComponent>? _modControlEntity;

    private Dictionary<EntityUid, (SwitchButton, ModuleInfoControl)> _gridControls = new();

    public Action<EntityUid, bool>? OnModuleToggled;
    
    public ModsuitControllerWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void Initialize(Entity<ModsuitControllerComponent, ModuleStorageComponent> entity)
    {
        _modControlEntity = entity;
        SpriteView.SetEntity(_modControlEntity.Value);
        var name = new FormattedMessage();
        name.PushColor(Color.White);
        name.AddText(Identity.Name(_modControlEntity.Value, _entity));
        ControlName.SetMessage(name);
        Update();
    }

    public void Update()
    {
        if (_modControlEntity == null)
            return;

        var seen = new Dictionary<EntityUid, bool>();
        foreach (var entUid in _gridControls.Keys)
        {
            seen[entUid] = false;
        }
        
        foreach (var module in _modControlEntity.Value.Comp2.ModuleSlots.Values)
        {
            if (module is null)
                continue;

            if (_entity.TryGetComponent<ItemToggleComponent>(module, out var toggleComp))
            {
                if (_gridControls.TryGetValue(module.Value, out var controls))
                {
                    controls.Item1.Pressed = toggleComp.Activated;
                    seen[module.Value] = true;
                } 
                else
                {
                    var button = new SwitchButton
                    {
                        ToggleMode = true,
                        Pressed = toggleComp.Activated,
                        MinWidth = 100.0f
                    };
                    button.OnToggled += e => OnModuleToggled?.Invoke(module.Value, e.Pressed);
                    var moduleInfo = new ModuleInfoControl(module.Value, _entity);
                    ToggleGrid.AddChild(button);
                    ToggleGrid.AddChild(moduleInfo);
                    _gridControls.Add(module.Value, (button, moduleInfo));
                }
            }
        }

        foreach (var entUpdated in seen)
        {
            if (entUpdated.Value)
                continue;
            
            var controls = _gridControls[entUpdated.Key];
            ToggleGrid.RemoveChild(controls.Item1);
            ToggleGrid.RemoveChild(controls.Item2);
            _gridControls.Remove(entUpdated.Key);
        }

        var uiFunctional = _modControlEntity.Value.Comp1.UIFunctional;
        foreach (var controls in _gridControls.Values)
        { 
            controls.Item1.Disabled = !uiFunctional;
            controls.Item2.SetScrambled(!uiFunctional);
        }
        UIErrorLabel.Visible = !uiFunctional;
    }
    
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_modControlEntity == null)
            return;

        var powerSystem = _entity.System<PowerCellSystem>();
        var batterySystem = _entity.System<BatterySystem>();

        if (!powerSystem.TryGetBatteryFromSlotOrEntity(_modControlEntity.Value.Owner, out var battery))
        {
            NoCellLabel.Visible = true;
            ChargeBar.Visible = false;
            return;
        }

        NoCellLabel.Visible = false;
        ChargeBar.Visible = true;

        // These are just all from APC Menu. It'd be neat if they were pulled out into a separate control.
        // But I'm done making changes to upstream systems.
        var charge = batterySystem.GetChargeLevel(battery.Value.AsNullable());
        ChargeBar.Value = charge;
        ChargePercentage.Text = Loc.GetString("apc-menu-charge-label", ("percent", charge.ToString("P0")));
        UpdateChargeBarColor(charge);
    }
    
    private void UpdateChargeBarColor(float charge)
    {
        if (ChargeBar == null)
        {
            return;
        }

        var normalizedCharge = charge / ChargeBar.MaxValue;

        const float leftHue = 0.0f; // Red
        const float middleHue = 0.066f; // Orange
        const float rightHue = 0.33f; // Green
        const float saturation = 1.0f; // Uniform saturation
        const float value = 0.8f; // Uniform value / brightness
        const float alpha = 1.0f; // Uniform alpha

        // These should add up to 1.0 or your transition won't be smooth
        const float leftSideSize = 0.5f; // Fraction of ChargeBar lerped from leftHue to middleHue
        const float rightSideSize = 0.5f; // Fraction of ChargeBar lerped from middleHue to rightHue

        float finalHue;
        if (normalizedCharge <= leftSideSize)
        {
            normalizedCharge /= leftSideSize; // Adjust range to 0.0 to 1.0
            finalHue = MathHelper.Lerp(leftHue, middleHue, normalizedCharge);
        }
        else
        {
            normalizedCharge = (normalizedCharge - leftSideSize) / rightSideSize; // Adjust range to 0.0 to 1.0.
            finalHue = MathHelper.Lerp(middleHue, rightHue, normalizedCharge);
        }

        // Check if null first to avoid repeatedly creating this.
        ChargeBar.ForegroundStyleBoxOverride ??= new StyleBoxFlat();

        var foregroundStyleBoxOverride = (StyleBoxFlat) ChargeBar.ForegroundStyleBoxOverride;
        foregroundStyleBoxOverride.BackgroundColor =
            Color.FromHsv(new Vector4(finalHue, saturation, value, alpha));
    }
}