using Content.Client.UserInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Random;
using Robust.Shared.Utility;

namespace Content.Client._DEN.Clothing.Modsuits.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class ModuleInfoControl : BoxContainer, IEntityControl
{
    [Dependency] private readonly IRobustRandom _random = default!;
    
    private readonly EntityUid _entity;

    private static readonly int[] Cycles = [0, 1, 2, 3];
    
    public ModuleInfoControl(EntityUid entity, IEntityManager entityManager)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        _entity = entity;
        ModuleName.Text = entityManager.GetComponent<MetaDataComponent>(entity).EntityName;
        SpriteView.SetEntity(entity);

        var brokenSprite = new SpriteSpecifier.Rsi(new ResPath("_DEN/Interface/Modsuits/ui_fried.rsi"),
            "cycle-" + _random.Pick(Cycles));
        
        BrokenIcon.SetFromSpriteSpecifier(brokenSprite);
        BrokenIcon.DisplayRect.Stretch = TextureRect.StretchMode.Scale;
    }

    public EntityUid? UiEntity => _entity;
}