using Content.Client.UserInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Random;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._DEN.Clothing.Modsuits.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class ModuleInfoControl : BoxContainer, IEntityControl
{
    [Dependency] private readonly IRobustRandom _random = default!;
    private readonly IEntityManager _entityManager;
    
    private readonly EntityUid _entity;

    private bool _scrambled = true;

    private float _curFrameTime;

    private const float ScrambleDelay = 0.25f;
    private static readonly string[] Cycles = ["cycle-0", "cycle-1", "cycle-2", "cycle-3"];

    private static readonly char[] ScrambleText =
    [
        'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
        'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
        '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', '-', '=', '+',
        '/', '\\', '!', '@', '#', '$', '%', '^', '&', '*'
    ];
    
    public ModuleInfoControl(EntityUid entity, IEntityManager entityManager)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        _entity = entity;
        _entityManager= entityManager;
        ModuleName.Text = entityManager.GetComponent<MetaDataComponent>(entity).EntityName;
        SpriteView.SetEntity(entity);

        var brokenSprite = new SpriteSpecifier.Rsi(new ResPath("_DEN/Interface/Modsuits/ui_fried.rsi"),_random.Pick(Cycles));
        BrokenIcon.SetFromSpriteSpecifier(brokenSprite);
        BrokenIcon.DisplayRect.Stretch = TextureRect.StretchMode.Scale;
        _curFrameTime = ScrambleDelay;
    }

    public void SetScrambled(bool scrambled)
    {
        _scrambled = scrambled;
        if (!_scrambled)
        {
            ModuleName.Text = _entityManager.GetComponent<MetaDataComponent>(_entity).EntityName;
            BrokenIcon.Visible = false;
            SpriteView.Visible = true;
        }
        else
        {
            BrokenIcon.Visible = true;
            SpriteView.Visible = false;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        
        if (_scrambled)
        {
            _curFrameTime -= args.DeltaSeconds;
            if (_curFrameTime <= 0)
            {
                _curFrameTime = ScrambleDelay;
                // This should probably never be null but just in case.
                var text = ModuleName.Text?.ToCharArray() ?? [' '];
                var toScramble = _random.Next(5);
                for (int i = 0; i < toScramble; i++)
                {
                    text[_random.Next(text.Length)] = _random.Pick(ScrambleText);
                }

                ModuleName.Text = new(text);
            }
        }
    }

    public EntityUid? UiEntity => _entity;
}