using Content.Shared._DEN.CCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class DenTab : Control
{
    public DenTab()
    {
        RobustXamlLoader.Load(this);

        Control.AddOptionCheckBox(DenCCVars.HideLanguageFonts, HideLanguageFonts);
    }
}
