using Content.Client._DEN.Language.EntitySystems;
using Content.Client.Options.UI;
using Content.Shared._DEN.CCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class DenTab : Control
{
    public DenTab()
    {
        RobustXamlLoader.Load(this);

        Control.AddOptionDropDown(DenCCVars.HideLanguageFonts,
            HideLanguageFonts,
            [
                new OptionDropDownCVar<HideLanguageFontSetting>.ValueOption(HideLanguageFontSetting.None,
                    Loc.GetString("ui-options-language-hide-fonts-none")),
                new OptionDropDownCVar<HideLanguageFontSetting>.ValueOption(HideLanguageFontSetting.All,
                    Loc.GetString("ui-options-language-hide-fonts-all")),
                new OptionDropDownCVar<HideLanguageFontSetting>.ValueOption(HideLanguageFontSetting.Understood,
                    Loc.GetString("ui-options-language-hide-fonts-understood")),
            ]);

        IoCManager.Resolve<LanguageSystem>().OnLanguagesEnabledUpdate += OnLanguageEnableChanged;
    }

    private void OnLanguageEnableChanged(bool enabled)
    {
        HideLanguageFonts.Visible = enabled;
    }
}
