using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DEN.Containers.UI;

[GenerateTypedNameReferences]
public sealed partial class ContainerSelectionWindow : FancyWindow
{
    public ContainerSelectionWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetWindows(IEnumerable<BoxContainer> containers)
    {
        Options.RemoveAllChildren();
        foreach (var container in containers)
        {
            Options.AddChild(container);
        }
    }
}
